server:
  port: 8080
spring:
  application:
    name: UpFIle
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
up-file:
  folder-path: /root/Docker/UpFile/upData/folder
  file-path: /root/Docker/UpFile/upData/file
  show-path: /root/Docker/UpFile/upData
#  folder-path: E:/project/UpFIle/src/main/resources/folder
#  file-path: E:/project/UpFIle/src/main/resources/file
#  show-path: E:/project/UpFIle/src/main/resources
